### ISSUE TITLE
startup problems reported by kirktindel on https://wled.discourse.group/t/call-different-presets-from-alexa/306/7

### ISSUE THREAD

**Issue by siggel** [siggel/WLED#1]
### What happened?

 I have tried repeatedly to use the flasher to pull down both versions of the D1 Mini bin file you created, and the WLED SSID never shows up. In fact all that happens is a boot loop on the D1 mini device that keeps telling me the checksum.

I’m using ESPhome Flaster 1.1.0 because all other versions are blocked by Windows currently. I really want to use your version but I’m not sure how to get it loaded on my device. Can you help please?

Thanks

### To Reproduce Bug

Yes, this is a known working ESP8266 with 4mb memory. When I use that same ESP Flasher program to upload the latest WLED release, it works fine and I see the WLED-AP SSID even before it’s been power cycled. When I use the two bin files on the page you referenced in the link above, it seems to push the software okay but I notice the following behavior:

1: Blue LED on the board doesn’t stay lit, only blinks for about 1/8th of a second every ~7 seconds (it stays lit solid with current WLED release)
2: WLED-AP SSID never shows up (it shows up on current WLED)
3: The ESP Flasher serial monitor shows repeated resets of the ESP8266 even after power-cycle
(text under “Showing Logs” repeats every few seconds):
Using ‘COM3’ as serial port.
Writing at 0x00078000… (100 %)Wrote 746320 bytes (504504 compressed) at 0x00000000 in 45.0 seconds (effective 132.7 kbit/s)…
Hash of data verified.

Leaving…
Hard Resetting…
Done! Flashing is complete!

Showing logs:
[07:58:40]s$[07:58:40] ets Jan 8 2013,rst cause:4, boot mode:(3,6)
[07:58:40]
[07:58:40]wdt reset
**[07:58:40]load 0x4010f000, len 3584, room 16 **
[07:58:40]tail 0
[07:58:40]chksum 0xb0
[07:58:40]csum 0xb0
[07:58:40]v3969889e
[07:58:40]~ld
[07:58:48]
[07:58:48] ets Jan 8 2013,rst cause:4, boot mode:(3,6)
[07:58:48]
[07:58:48]wdt reset
**[07:58:48]load 0x4010f000, len 3584, room 16 **
[07:58:48]tail 0
[07:58:48]chksum 0xb0
[07:58:48]csum 0xb0
[07:58:48]v3969889e
[07:58:48]~ld
[07:58:57]
[07:58:57] ets Jan 8 2013,rst cause:4, boot mode:(3,6)
[07:58:57]
[07:58:57]wdt reset
**[07:58:57]load 0x4010f000, len 3584, room 16 **
[07:58:57]tail 0
[07:58:57]chksum 0xb0
[07:58:57]csum 0xb0
[07:58:57]v3969889e
[07:58:57]~ld

Also, if it matters - this is the black PCB ESP8266 30-pin 2-button. I’ve got probably 30 or 40 of these laying around, I’ve tried on multiple different boards and the most current WLED release bin files works great, the ones I actually want (yours) have this same behavior. I asked a friend to try on his and he gets the same thing. Can you try it on one of yours and see if you also get the same behavior? If not, I’m wondering what may be different about your hardware? The one I’m trying this on now was just taken out of the package brand new as of a few minutes ago.

Oh, and one last thing… thank you! I can’t wait to get this working. What a great idea!

### Expected Behavior

starts up and provides webui

### Install Method

Self-Compiled

### What version of WLED?

like provided here

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by siggel** [comment]
Just to answer the very basic things:

- I use D1 mini 12F like these: https://www.amazon.de/AZDelivery-D1-Mini-Entwicklungsboard-kompatibel/dp/B0754N794H/
- I use FlashESP8266.exe tool which is very basic
- for flashing D1 mini is connected via micro usb with CH34x driver

**Comment by siggel** [comment]
Startup problem confirmed when starting from my D1 mini erased by a 4MB blank image :( Investigating... Maybe leaving the loop over all presets does not work as maybe "start without presets" behaves differently from "having had presets by a previous original WLED version and deleted them"? Currently the condition looks like
`String name = getPresetName(presetIndex);`
`if (name == "") break; // no more presets`

**Comment by siggel** [comment]
This is really strange... I just built it again without changing my sources, erased the D1 mini again with the blank 4MB image and flashed the new image to it => works immediately without knowing any presets yet.

**Comment by siggel** [comment]
@kirktindel, could you please try, if the new V3 release works for you too? I'm running out of ideas what could be the difference between previous versions having worked before but not today and V3 running now in my setup but maybe not for you? The only remaining idea could be that I may always have used each of my D1 minis for code development beforehand, such that they had been flashed before via the Visual Studio Code setup which is described in the WLED project. MAYBE today's D1 mini had never seen Visual Studio Code before and today's building a new image using that D1 mini has changed something important that survives the erasing procedure and is required for Visual Studio Code generated images to run.

**Comment by kirktindel** [comment]
It works!!!  Whatever you did works perfectly now!!

Thank you so much!  This is awesome!!!

**Comment by kirktindel** [comment]
Hey can I make a donation or something? This solves a huge problem for me.  Frankly this should be in the main fork.  It adds so much versatility to this platform.

**Comment by siggel** [comment]
Hi @kirktindel
thanks for your feedback. Your enthusiasm about my work is reward enough. Only favor you could do me is that you promote it around your friends that may be interested too. The more people use it, the better the chance to detect errors that I never came across. Until your feedback I was wondering if anyone was interested in it at all anymore. Admittedly I don't even use it either, I just created it for my son because installing an own smart home central for that task would have been kind of overengineering. My only LED strip is only triggered by my smarthome central in case of certain events - including events from that nerdy Aqara cube (just in case you are looking for other impressive ways to trigger effects, but be warned: connecting the cube to my non Aqara Zigbee gateway was a nightmare)
Although not using it myself I would be willing to bring my fork back into the main fork, but frankly speaking I did some dirty reverse engineering on what I understood from the rather undocumented code. I came around a lot of ifdefs and had no idea what those branches in the code are meant for, so I just made the D1 mini path work. I hope that if the feature gets more visible interest that some of the original authors may assist or at least review it. Probably a long way to go... In the current state I think it may break on 90% of different devices :(
If you happen to require a more up to date base version of WLED due to some new indispensable feature on the orginal fork some day, feel free to create an issue here requesting to merge an up to date main fork into my branch. Just normally expect some longer processing time and be warned you may be the first to test it if I don't have all parts for testing at hand immediately :)
LLAP,
siggel
