### ISSUE TITLE
Announce integration of Alexa extension into official WLED

### ISSUE THREAD

**Issue by siggel** [siggel/WLED#2]
@kirktindel @sangera2 @bennony

Hope I address the correct users here on Github that showed interest in my Alexa extension to WLED on discourse, otherwise just ignore me :)

I think it may be relevant news for you: My Alexa extension made it into the official WLED repository. So you should be able to profit from new WLED features while preserving the extended Alexa functionality as soon as a new WLED release is created from the main branch.
For not bothering people that do not want that feature, the default setting will support only the original Alexa device from the configuration. You can configure at the same location, that you want to enable the first n presets in Alexa, i.e. setting n=9 will equal to the behavior that you know.

Of course you can still contact me if questions for that feature arise, but the community on discourse may answer quicker as I'm not actively involved in the development of WLED but rather contributed by chance. But of course I'll stay committed to maintain my contribution - and maybe some day I might find another WLED code fragment to tinker with out of interest :)

**Comment by bennony** [comment]
My congratulations, it's nice that more can now benefit from it ;-)

(As once written it would be nice if you could check out a sound reactive version and bring Alexa to life with your extension)

**Comment by ScriptSorcererUK** [comment]
Now we have to wait for aircookie to release a binary though! 😊 Glad I flashed your v4 recently on my devices. It works great BTW. Thanks very much for your time and persistence!
